# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49820e4c02cd0ef62ba3c0795d8517329e120ab097d861eb2c22f908b9a093870d83a1a7f341108438f7ab2c07294aa38e3fe8bf6a7a7ef8b384fd75b3947c17

test:
  secret_key_base: 717766791ac8d85082617b19949cc2613fbee9e981bc190faecb763c519f9388cd95983f65b5068b6d7f0c8f0685af43db152a607c10aee70c6985993bfbeefc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
